# Generated by Django 4.1.2 on 2023-10-08 11:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('codeAnly', models.AutoField(primary_key=True, serialize=False, verbose_name='Numero')),
                ('dateAnly', models.DateField(default=datetime.date.today, verbose_name='Date de Demande')),
                ('cardeAnly', models.CharField(max_length=100, verbose_name='Card')),
                ('natureAnly', models.CharField(max_length=50, verbose_name='Nature')),
                ('typeAnly', models.CharField(max_length=50, verbose_name='Type')),
                ('echantillonAnly', models.IntegerField(verbose_name="Nombre d'chantillon")),
            ],
        ),
        migrations.CreateModel(
            name='Appareil',
            fields=[
                ('idApr', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name="Code d'Appareil")),
                ('numSerieApr', models.CharField(max_length=20, verbose_name="Numero d'Serie")),
                ('designationApr', models.CharField(max_length=100, verbose_name="Nom d'Appareil")),
                ('frequenceMaintenanceApr', models.IntegerField(verbose_name='Frequence de Maintenance Par jour')),
                ('dateAchatApr', models.DateField(verbose_name="Date d'Achat")),
                ('marqueApr', models.CharField(max_length=50, verbose_name='Marque')),
                ('FournisseurApr', models.CharField(max_length=100, verbose_name='Fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('codeArt', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Code')),
                ('designationArt', models.CharField(max_length=150, verbose_name='Designation')),
                ('typeArt', models.BooleanField(default=True, verbose_name='is Produit Chimique')),
                ('fournisseurArt', models.CharField(max_length=100, verbose_name='Fournisseur')),
                ('stockMinArt', models.FloatField(verbose_name='Stock Minimum')),
                ('stockMaxArt', models.FloatField(verbose_name='Stock Minimum')),
                ('moyLivraisonArt', models.IntegerField(verbose_name='moyen de Livraison par jour')),
                ('natureArt', models.CharField(max_length=50, verbose_name='Nature')),
                ('marqueArt', models.CharField(max_length=50, verbose_name='Marque')),
            ],
        ),
        migrations.CreateModel(
            name='Chercheur',
            fields=[
                ('matriculeChr', models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='Matricule')),
                ('nomChr', models.CharField(max_length=50, verbose_name='Nom')),
                ('prenomChr', models.CharField(max_length=50, verbose_name='Prenom')),
                ('mailChr', models.EmailField(max_length=254, verbose_name='Email')),
                ('telChr', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telephone ')),
                ('photoChr', models.ImageField(upload_to='chercheur', verbose_name='photo source')),
                ('specialiteChr', models.CharField(max_length=100, verbose_name='Specialite')),
                ('userChr', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('codeLabo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero')),
                ('designationLabo', models.CharField(max_length=50, verbose_name='Nom')),
                ('departementLabo', models.CharField(choices=[('chimie macromoléculaire', 'Chimie Macromoleculaire'), ('chimie et physique des matériaux inorganiques', 'Chimie Et Physique Des Materiaux Inorganiques'), ('chimie organique', 'Chimie Organique'), ('chimie physique et théorique', 'Chimie Physique Et Throrique')], max_length=50, verbose_name='Département de')),
                ('matriculeChr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.chercheur', verbose_name='Chef de Laboratoire')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=256)),
                ('photo', models.ImageField(null=True, upload_to='sliders/')),
                ('contenue', models.TextField(max_length=5000)),
                ('lien', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('codeStock', models.AutoField(primary_key=True, serialize=False, verbose_name='Numero')),
                ('entreStock', models.BooleanField(verbose_name='is Entre')),
                ('qtStock', models.FloatField(verbose_name='Quantite')),
                ('dateStock', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('codeArt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.article', verbose_name='Article')),
            ],
        ),
        migrations.CreateModel(
            name='Stagiare',
            fields=[
                ('codeStg', models.AutoField(primary_key=True, serialize=False, verbose_name='Numero')),
                ('themeStg', models.CharField(max_length=150, verbose_name='Theme')),
                ('debutStg', models.DateField(verbose_name='Debut de Stage')),
                ('finStg', models.DateField(verbose_name='Fin de Stage')),
                ('codeLabo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.laboratoire', verbose_name='Laboratoire')),
                ('encadreur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encadreurs', to='base.chercheur', verbose_name='Encadreur')),
                ('matriculeChr1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculeChrs_1', to='base.chercheur', verbose_name='Stagiare')),
                ('matriculeChr2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculeChrs_2', to='base.chercheur', verbose_name='Stagiare')),
            ],
        ),
        migrations.CreateModel(
            name='Rendez_vou',
            fields=[
                ('codeRndv', models.AutoField(primary_key=True, serialize=False, verbose_name='Code Rendez-vous')),
                ('dateRndv', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('depuisRndv', models.TimeField(verbose_name='de puis')),
                ('jusquaRndv', models.TimeField(verbose_name="jusqu'a")),
                ('obsRndv', models.TextField(max_length=2000, verbose_name='Observation')),
                ('codeanly', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.analyse', verbose_name='Numero de demande')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('codeExp', models.AutoField(primary_key=True, serialize=False, verbose_name='Code Experience')),
                ('dateExp', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('titreExp', models.CharField(max_length=150, verbose_name='Titre')),
                ('methodeExp', models.TextField(max_length=5000, verbose_name='MethodeExp')),
                ('conclusionExp', models.TextField(max_length=5000, verbose_name='Conclusion')),
                ('codeChr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.chercheur', verbose_name='Chercheur')),
                ('idApr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.appareil', verbose_name='Appareil')),
            ],
        ),
        migrations.CreateModel(
            name='Echantillon',
            fields=[
                ('codeEch', models.AutoField(primary_key=True, serialize=False, verbose_name='code echantillon')),
                ('numEch', models.IntegerField(verbose_name='N°')),
                ('conditionOperatoireEch', models.TextField(max_length=1000, verbose_name='Condition Operatoire')),
                ('resultatEch', models.TextField(max_length=1000, verbose_name='Resultat')),
                ('codeExp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.experience')),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtDB', models.FloatField(verbose_name='Quantite Demande')),
                ('qtRB', models.FloatField(verbose_name='Quantite Receptionne')),
                ('codeArt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.article')),
                ('codeStg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.stagiare')),
            ],
        ),
        migrations.AddField(
            model_name='appareil',
            name='codeLabo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.laboratoire', verbose_name='Laboratoire'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='idApr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.appareil', verbose_name='Appareil'),
        ),
        migrations.AddField(
            model_name='analyse',
            name='matriculeChr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.chercheur', verbose_name='Chercheur'),
        ),
        migrations.AddConstraint(
            model_name='echantillon',
            constraint=models.UniqueConstraint(fields=('codeEch', 'numEch'), name='unique_codeech_numech_combination'),
        ),
    ]
